### ISSUE TITLE
defaultRequest в функции testException

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#10]
Зачем выполняется действие `httpLBS defaultRequest` в функции testException?

**Comment by AKitavtsev** [comment]
На самом деле, действие не выполняется, так, как до него вызывается функция initSession, из которой сюда возврата не будет. Но, как-то нужно обозначить тип IO (Response LBC.ByteString), что бы компилятор не ругался. Ничего проще не могу придумать. Понимаю, костыль какой-то. Может подскажешь, что в таких случаях надо делать. 

Пожалуйста, возвращай Issuue в open, если проблема остается открытой.

**Comment by olegromashin** [comment]
У меня нет прав, чтобы открывать закрытые ишью, лучше тогда ты не закрывай, я сам после ревью решения буду закрывать :)

**Comment by olegromashin** [comment]
> Может подскажешь, что в таких случаях надо делать.

Пока могу только сказать, что надо рефакторить те места, где вызывается функция testException. Чуть позже постараюсь более предметно посмотреть и описать, что можно поправить.

**Comment by AKitavtsev** [comment]
Спасибо, все понял, Я сам ничего не закрываю. Сейчас неисправленные открою. По testExeption  у меня тоже есть сомнения

**Comment by AKitavtsev** [comment]
### Сделано
