### ISSUE TITLE
Два стиля именования полей в конфиге

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#11]
В конфиге до сих пор применяютсядва стиля именования - один для настроек бота, второй для уровня логирования. Надо привести к одному стилю.

**Comment by AKitavtsev** [comment]
Я правильно, понял, что level и levelLog - это разные стили? Если да, то, исправлено, если, нет, поясни, пожалуйста, что ты имеешь в виду

**Comment by olegromashin** [comment]
> Я правильно, понял, что level и levelLog - это разные стили?

Нет, это один стиль. Я имел в виду файл конфига `bot.conf.template`. Там для уровня логирования используется второй стиль.

**Comment by AKitavtsev** [comment]
Спасибо, исправлю.
А я, неуч, думал, что это касается только Хаскеля,

**Comment by AKitavtsev** [comment]
Исправил
