### ISSUE TITLE
newDict и State

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#12]
Зачем используешь монаду State? Поменяется ли что-то, если выполнять вычисления без неё?

**Comment by AKitavtsev** [comment]
Не понял вопроса...
Без нее, наверняка, можно, но это будет другое решение.
А, как из этого легко убрать State, не понимаю.

**Comment by olegromashin** [comment]
> Не понял вопроса...

Ну вот ты использовал монаду State в том месте, где ты обновляешь словарь. Какой профит ты от этого получил? У тебя в стейте единственное вычисление запускается, которое заменяет старые записи новыми. Можно ли вместо запуска вычисления в монаде State обычную функцию поставить, которая будет делать тоже самое?

> Без нее, наверняка, можно, но это будет другое решение.

Чем оно будет отличаться?

Некоторые ишью я специально составляю вопросами, потому что необходимо научиться разбираться в таких вещах, чтобы иметь возможность осознанно применять инструменты. Если не можешь ответить или сомневаешься, то просто попробуй по-другому и напиши получилось или не получилось и почему)

**Comment by AKitavtsev** [comment]
Ну не понимаю. Профит? Я престо получаю довольно лаконичную и простую реализацию. 
У меня есть текущее состояние (state) и список апдейтов, каждый из которых мог изменить это состояние. Я просто с помощью mapЬ_ прохожусь по этому списку, пошагово изменяя состояние и получаю новое состояние. Чем не State,
Конечно, можно по-другому, но обычно я ищу другое решение, когда мне не нравится реализованное.
Что значит обычную функцию?  fun :: [UPD] -> MapInt -> MapInt ? У меня не вызывает никаких мыслей. Подскажи, пожалуйста

**Comment by olegromashin** [comment]
> Я просто с помощью mapЬ_ прохожусь по этому списку, пошагово изменяя состояние и получаю новое состояние.

Можно ли пройтись по MapInt заменяя все значения новыми из [UPD] без использования монады State?

**Comment by AKitavtsev** [comment]
Опять не понял. Как это пройтись по MapInt, это же Map? Да и в [UPD} нет никаких значений для MapInt.
Наверное, все же можно. Перебрать все ключи в  MapInt, проверив нет ли изменения значения, в каком-нибудь из UPDи изменить это значение. 
Но, что за Профит? До еще с учетом того, что значение ключа могло изменятся неоднократно

Нет, я чего-то не понимаю

**Comment by olegromashin** [comment]
Смотри, у тебя в DataLoop хранятся dictionary и updates. Из апдейтов ты берёшь пользователя и кол-во повторений и обновляешь dictionary. Вот такую функцию можно без стейта написать или нет:
```
updateDictionary :: MapInt -> [(Int, Int)] -> MapInt
updateDictionary dictionary updates = ...
```
Если всё же не понимаешь меня, то напиши. Тогда по-другому попробую.

**Comment by AKitavtsev** [comment]
А я гордился, что и освоил и применил State. А все свелось к элементарной рекурсии... (

**Исправлено**

**Comment by olegromashin** [comment]
Ну просто в твоём применении не было никакого смысла. Если будет время, можешь применить State как надо, это должно помочь понять как им пользоваться: убрать DataLoop из хэндла и перенести его в State. запускать цикл бота в монаде State.
