### ISSUE TITLE
Добавление коммитов

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#14]
Сообщения коммитов должны отражать суть изменений, которые в них находятся. При просмотре истории коммитов не должно возникать необходимости открывать ишью по номеру (как это надо делать сейчас) и находить суть изменений. Кроме того коммиты надо делить на осмысленные части. Пихать изменения по всем ишью в один коммит плохо - это затрудняет ревью и в случае необходимости откатить изменения всё очень усложнится.

**Comment by AKitavtsev** [comment]
Сколько примерно текста надо вкладывать в комментарий коммита (мин - макс символов) ?

**Comment by olegromashin** [comment]
Я бы не сказал, что это такая мера, на которую стоит опираться. Главное, чтобы была передана суть очень кратко, но в то же время более-менее описательно. Тем не менее отвечу - обычно я укладываюсь в 30-40 символов. Стараюсь не переваливать за 70 символов.

**Comment by AKitavtsev** [comment]
Спасибо, понял

**Comment by AKitavtsev** [comment]
### Исправился

**Comment by olegromashin** [comment]
Здесь надо ещё немножко поработать.
Смотри, например сообщение последнего коммита `MapInt -> UserRepetition`. Непонятно что здесь имеется в виду. В контексте Хаскеля можно подумать, что ты написал функцию, которая конвертирует значения из MapInt в UserRepetition. Лучше в будущем явно писать, что переименовал MapInt в UserRepetition.
Или например вот этот коммит: `Whithout fromJust and read, without further comment` - во-первых ты здесь две задачи сделал и по-хорошему надо было отдельно убрать комментарии и отдельно отрефакторить код. Во-вторых `without further comment` опять же не очень понятно. Если перевести, то, что ты написал, то получается "без дальнейших комментариев". Если на английском пока не очень уверенно пишешь, то в переводчик просто загоняй "удалил лишние комментарии" и всё)
