### ISSUE TITLE
Удалить лишние комментарии

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#16]
Оставлять закомментированные участки кода без описания причины - плохая практика. Никто кроме тебя потом не будет знать что с этим делать и такие комментарии могут остаться очень надолго, если не навсегда, т. к. непонятно можно их трогать или нет. Кроме этого они затрудняют чтение кода. Ещё в некоторых местах есть пустые комментарии, они немного сбивают с толку, т. к. кажется, что ты хотел сделать на чём-то акцент.

**Comment by AKitavtsev** [comment]
Просто, когда кардинально меняю я код, я комментирую старый, что бы его сохранить на некоторое время. Потом, конечно удаляю. Изначально, когда я подавал на ревю, там было все чисто. В процессе что-то появляется, но достаточно быстро удаляется. Или необходимо перед каждым коммитом очищать?

**Comment by olegromashin** [comment]
А зачем тебе старый код на некоторое время? Всё это есть в коммитах и ты в любой момент можешь откатить изменения или просто посмотреть как было.

> необходимо перед каждым коммитом очищать?

Да, такого быть не должно по причинам описанным выше.

**Comment by AKitavtsev** [comment]
Понял, оправлюсь

**Comment by AKitavtsev** [comment]
### Сделано

**Comment by olegromashin** [comment]
Остался ещё закомментированный без причины код в модулях BotTest и Bot (в тестах кстати неиспользуемые расширения остались).

**Comment by AKitavtsev** [comment]
###Сделано
Но, оставил пару строчек в Bot (пока у нас остаются две главный проблемы - InitSession и testException).
