### ISSUE TITLE
Handle для конфига

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#19]
Не могу понять зачем ты решил для получения конфига сделать хэндл. Предлагаю обычную IO-функцию сделать. Ну или если есть причина, то напиши)

**Comment by AKitavtsev** [comment]
По тем же причинам, что и логгер. Что бы сделать конфиг в виде сервиса,  изолировать его зависимость от внешних библиотек и т, д. Что бы было сервис паттерн. Что бы его не факторили, а просто написали другую реализацию использую аннатацию из хэндла и любые другие библиотеки. Чем конфиг хуже логгера? Или я опять что-то не понял?
Только скажи, что надо убрать - уберу. Вместо двух модулей будет один.

**Comment by olegromashin** [comment]
В твоём проекте во всём этом нет необходимости. Конфиг используется только в одном месте. Если поменяется реализация, то даже без хэндла тебе нужно будет поменять только одно место в функции main. Логгер используется повсеместно, поэтому если тебе потребовалось бы поменять логгер, то без использования хэндла пришлось бы рефакторить весь проект.

**Comment by AKitavtsev** [comment]
### Исправлено
