### ISSUE TITLE
Когда выбираешь количество повторений у Telegram бота ничего не происходит

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#29]
Лог, который появляется при выбора числа повторений:
```
DEBUG List of Updates received = 
 [Update {update_id = 925360515, message = Nothing, callback_query = Just (CallbackQuery {cq_id = "3984560341692533090", cq_from = User {user_id = 927727749, user_is_bot = False, user_first_name = "Oleg"}, cq_data = Just "2"})}]
```

**Comment by AKitavtsev** [comment]
В смысле "ничего"?
Сценарий должен быть такой:
/repeat    -> появляется клавиатура 
жмешь на ней 2 -> сообщений никаких не поступает (в отличие от ВК), лог правильный
посылаешь сообщение -> в ответ получаешь два таких же сообщения
Что-то не так?

**Comment by olegromashin** [comment]
А, да, сорян. Я что-то забыл, что у тебя при нажатии на кнопку нет сообщения :)
Тогда всё ок, закрываю.
