### ISSUE TITLE
Описать работу с конфигом

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#3]
Сейчас, чтобы понять, что можно завести локальный конфиг надо лезть во внутренности. Опиши в ридми, что можно создать local_bot.conf.
Но вообще есть ещё минус. Можно случайно заполнить bot.conf, чтобы потыкаться, а потом случайно запушить заполненный конфиг. По-хорошему bot.conf надо переименовать в bot.conf.template, в ридми написать, что надо скопипастить этот файл, переименовать в нормальный bot.conf и работать с ним. При этом в gitignore у тебя останется только template файл.

**Comment by AKitavtsev** [comment]
Исправлено
