### ISSUE TITLE
Неиспользующиеся прагмы

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#6]
Во многих модулях включены лишние расширения и опции GHC, которые там не используются:
{-# OPTIONS_GHC -fno-warn-orphans #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE FlexibleContexts #-}
может ещё что-то есть.

**Comment by AKitavtsev** [comment]
Исправлено
