### ISSUE TITLE
fromJust

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/telegram-vk-bot#8]
Функция нетотальная и выбрасывает исключение, если получает Nothing. Использование таких функций считается плохой практикой, т. к. любой рефакторинг становится опасным. Если при написании кода ты был уверен, что получишь Just, то со временем это может изменится. Кроме этого, при таком подходе становится сложнее писать новый код. Придётся запоминать и проверять, не выбрасывает ли функция исключения, если принимает Maybe и получает Nothing. Надо исправить.

**Comment by AKitavtsev** [comment]
От FromJust не решился избавится. Но необходимые меры по безопасности осуществил:
1. Спрятал внутри функций, которые ее используют. Так, что ее никто другой ее использовать не будет.
2. Невозможность Nothing гарантируется документацией на api и контролируется внутри функций.
3. Но, даже, если какому-то талантливому рефакторщику удастся засунуть Nohting, он заслужит Exception, и настолько часто, что не сможет донести этого до юзера.
4. Можно еще поставить условия, что бы не было исключения, а все запросы будут приводить к респонсу с плохим статусом.
Может, так нормально? Не рекомендовано, не значит недопустимо. Зато функции выглядят изящно и читаемо

**Comment by olegromashin** [comment]
> Спрятал внутри функций, которые ее используют. Так, что ее никто другой ее использовать не будет.

Это не решило проблемы, описанные выше.

> Невозможность Nothing гарантируется документацией на api и контролируется внутри функций.

Зачем тогда использовать Maybe?

>Но, даже, если какому-то талантливому рефакторщику удастся засунуть Nohting, он заслужит Exception, и настолько часто, что не сможет донести этого до юзера.

Получается мне (и всей команде, и тебе в том числе) или придётся зарываться в твой код и запоминать все его внутренние детали работы, или придётся бороться с исключениями, которые я не мог предвидеть. 

В твоём проекте тебе, возможно, кажется, что здесь нет ничего очень уж плохого и код довольно очевидный, но необходимо научиться правильно писать код на таком маленьком проекте, потому что на больших проектах ты за всем не уследишь. Когда пишешь код, нельзя полагаться на предположения "никто не будет использовать эту функция по-другому" или "здесь не может быть Nothing". Что будет если API изменится? В твоём случае ничего страшного, если что-то пойдёт не так, а в нормальных проектах может пострадать база данных и пользователи.

**Comment by AKitavtsev** [comment]
Я понял, проект учебный. Дискуссию на  эту  моего FromJust больше не ведем. Исправляю.

Но, в связи с вышесказанным позволь пару вопросов (для опыта на будущее):
1. Как я могу полностью избежать неприятностей, если изменится API, Неужели возможно в коде проверять, а так ли это, как сказано в документации, как , а не изменилось ли там что (но ведь есть номер версии API, к которому привязано мое приложение.
2. Например, в документации сказано :"'есть два поля (вот почему, я использую Maybe), и всегда одно из них Just, второе Nothing". На практике, участвуя в крупных проектах, я не смогу на это полагаться, и должен, как то извернуться, и проверить, а не сможет там оказаться два Just или два Nothing ?
3.  В документации: "'это поле String содержит номер (целое число)". Я буду должен проверить это, перед тем, как использовать read ::Integer? Или, вообще не использовать read (так, как функция не тотальна)?

**Comment by AKitavtsev** [comment]
Исправлено

**Comment by olegromashin** [comment]
До сих пор вижу применение функции fromJust в модулях Bot.VK и Bot.Telegram.Internal.

**Comment by AKitavtsev** [comment]
Так я же непосредственно перед обращением к ней проверяю на isNohting
Понимаю, что кто-то может к ней обратиться, не проверив. Хорошо, вместо fromJust, я пишу (\Just x-> x). Так можно? Теперь никто не сможет обратиться к моей функции. Логично?
Ты почему-то не обратил внимания на последние мои вопросы на эту тему

**Comment by olegromashin** [comment]
> Как я могу полностью избежать неприятностей, если изменится API, Неужели возможно в коде проверять, а так ли это, как сказано в документации, как , а не изменилось ли там что (но ведь есть номер версии API, к которому привязано мое приложение.

При внесении изменений в API новые версии стараются делать обратно совместимыми с предыдущими версиями, в противном случае неприятностей не избежать. Но я не вижу как связан этот вопрос с тем, что мы в ишью обсуждаем.

> Например, в документации сказано :"'есть два поля (вот почему, я использую Maybe), и всегда одно из них Just, второе Nothing". На практике, участвуя в крупных проектах, я не смогу на это полагаться, и должен, как то извернуться, и проверить, а не сможет там оказаться два Just или два Nothing ?

Если поле в API всегда присутствует (всегда Just), то зачем там использовать Maybe? И наоборот, если поле отсутствует (Nothing), то зачем добавлять его в тип? Если же ты делаешь универсальный тип под разные API, то будь готов везде добавлять проверки.

> В документации: "'это поле String содержит номер (целое число)". Я буду должен проверить это, перед тем, как использовать read ::Integer? Или, вообще не использовать read (так, как функция не тотальна)?

Мы стараемся использовать `readMaybe` и выбрасывать описательную ошибку в случае Nothing, вместо `Prelude.read: no parse`

> Так я же непосредственно перед обращением к ней проверяю на isNohting
Понимаю, что кто-то может к ней обратиться, не проверив. Хорошо, вместо fromJust, я пишу (\Just x-> x). Так можно? Теперь никто не сможет обратиться к моей функции. Логично?

Если у тебя уже есть проверка на Nothing и ты достаёшь значение из Just в случае Just, то почему тогда не использовать безопасный паттерн матчинг? Логично, конечно, что сейчас твоя функция полностью безопасна, но суть в том, что мы стараемся нигде не добавлять даже малейшую возможность ошибки (только если этого не избежать). Твоя функция, например, со временем может разрастись и проверка на Nothing может изменится. Если наставить таких мин по проекту, то со временем какая-нибудь рванёт. Закон Мерфи :)

**Comment by AKitavtsev** [comment]
Если` поле в API всегда присутствует (всегда Just), то зачем там использовать Maybe? И наоборот, если поле отсутствует (Nothing), то зачем добавлять его в тип? Если же ты делаешь универсальный тип под разные API, то будь готов везде добавлять `проверки.

Не так. В API обязательно присутствует одно из двух полей. Причем только одно и неизвестно, какое. Поэтому оба Maybe.

Если у тебя уже есть проверка на Nothing и ты достаёшь значение из Just в случае Just, то почему тогда не использовать безопасный паттерн матчинг? 

Я просто ну никак не могу понять, что должна вернуть функция , если я просто хочу распаковать Just, а там по каким-то непонятным причинам Nothing. Но если Nothing - тогда это ошибочная ситуация. Если мы в IO, тогда можно эту ситуацию как-то обработать, не допустить эксепшина. Но, если это чистая функция, возвращающая какой-то конкретный тип ? Что тут можно сделать.

А, что мой вариант с лямбда не проходит?

**Comment by olegromashin** [comment]
> Не так. В API обязательно присутствует одно из двух полей. Причем только одно и неизвестно, какое. Поэтому оба Maybe.

Почему тогда тип-сумму не использовал?

> Но, если это чистая функция, возвращающая какой-то конкретный тип ? Что тут можно сделать.

Сделать возвращаемое значение Maybe и когда вычисление возвращается в IO обработать также, как остальные ошибки.

> А, что мой вариант с лямбда не проходит?

Не подходит по причинам описанным выше. В твоём проекте он, может, и не такой страшный, но на реальных проектах такое не пройдёт через ревью.

**Comment by AKitavtsev** [comment]
### Исправлено
